ERROR - 2022-12-16 11:37:11 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'stdp' in D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', '', 'stdp', 3306, '', 0)
#1 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\laragon\www\stdp\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 D:\laragon\www\stdp\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 D:\laragon\www\stdp\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(119): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\stdp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'stdp' in D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\laragon\www\stdp\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 D:\laragon\www\stdp\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 D:\laragon\www\stdp\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(119): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\stdp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-16 11:37:11 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'stdp'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 APPPATH\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 APPPATH\ThirdParty\myth-auth\src\Controllers\AuthController.php(119): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-16 15:47:08 --> mysqli_sql_exception: Unknown column 'alamat' in 'field list' in D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1778): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 D:\laragon\www\stdp\app\Database\Seeds\anggota.php(49): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#5 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\Seeder.php(146): App\Database\Seeds\anggota->run()
#6 D:\laragon\www\stdp\app\Database\Seeds\RUNALL.php(6): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\Seeder.php(146): App\Database\Seeds\RUNALL->run()
#8 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#9 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Seed->run(Array)
#10 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('db:seed', Array)
#11 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#12 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#13 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 D:\laragon\www\stdp\spark(98): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-12-16 15:47:28 --> mysqli_sql_exception: Duplicate entry '2' for key 'tbl_anggota.PRIMARY' in D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tb...', 0)
#1 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1778): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', NULL, false)
#4 D:\laragon\www\stdp\app\Database\Seeds\anggota.php(49): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#5 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\Seeder.php(146): App\Database\Seeds\anggota->run()
#6 D:\laragon\www\stdp\app\Database\Seeds\RUNALL.php(6): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\Seeder.php(146): App\Database\Seeds\RUNALL->run()
#8 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#9 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Seed->run(Array)
#10 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('db:seed', Array)
#11 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#12 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#13 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 D:\laragon\www\stdp\spark(98): CodeIgniter\CLI\Console->run()
#17 {main}
CRITICAL - 2022-12-16 16:46:21 --> syntax error, unexpected token ".", expecting identifier or variable or "{" or "$"
in APPPATH\Controllers\Anggota.php on line 64.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Anggota.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Anggota')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Anggota')
 4 SYSTEMPATH\CodeIgniter.php(877): class_exists('\\App\\Controllers\\Anggota', true)
 5 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-16 16:55:39 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `tbl_ang...', 0)
#1 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ang...')
#2 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ang...')
#3 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ang...', Array, false)
#4 D:\laragon\www\stdp\app\Controllers\Anggota.php(100): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Anggota->list_view_anggota()
#6 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Anggota))
#7 D:\laragon\www\stdp\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\laragon\www\stdp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-16 16:55:39 --> Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `tbl_anggota`.`nama_lengkap` as `nama_lengkap`, `tbl_anggota`.`jabatan` as `jabatan`, `tbl_anggota`.`no_telp` as `no_telp`, `tbl_anggota`.`alamat` as `alamat`, `users`.`active` as `active`, `users`.`username` as `username`, `users`.`email` as `email`, `tbl_anggota`.`log` as `log`, `tbl_anggota`.`foto` as `foto`, `tbl_anggota`.`tanggal_masuk` as `tanggal_masuk`, `users`.`id` as `user_id`
FROM `users`
JOIN `tbl_anggota` ON `users`.`anggota_id` = `tbl_anggota`.`id`
WHERE `user_id` = \'2\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_anggota`.`nama_lengkap` as `nama_lengkap`, `tbl_anggota`.`jabatan` as `jabatan`, `tbl_anggota`.`no_telp` as `no_telp`, `tbl_anggota`.`alamat` as `alamat`, `users`.`active` as `active`, `users`.`username` as `username`, `users`.`email` as `email`, `tbl_anggota`.`log` as `log`, `tbl_anggota`.`foto` as `foto`, `tbl_anggota`.`tanggal_masuk` as `tanggal_masuk`, `users`.`id` as `user_id`
FROM `users`
JOIN `tbl_anggota` ON `users`.`anggota_id` = `tbl_anggota`.`id`
WHERE `user_id` = \'2\'')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_anggota`.`nama_lengkap` as `nama_lengkap`, `tbl_anggota`.`jabatan` as `jabatan`, `tbl_anggota`.`no_telp` as `no_telp`, `tbl_anggota`.`alamat` as `alamat`, `users`.`active` as `active`, `users`.`username` as `username`, `users`.`email` as `email`, `tbl_anggota`.`log` as `log`, `tbl_anggota`.`foto` as `foto`, `tbl_anggota`.`tanggal_masuk` as `tanggal_masuk`, `users`.`id` as `user_id`
FROM `users`
JOIN `tbl_anggota` ON `users`.`anggota_id` = `tbl_anggota`.`id`
WHERE `user_id` = \'2\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_anggota`.`nama_lengkap` as `nama_lengkap`, `tbl_anggota`.`jabatan` as `jabatan`, `tbl_anggota`.`no_telp` as `no_telp`, `tbl_anggota`.`alamat` as `alamat`, `users`.`active` as `active`, `users`.`username` as `username`, `users`.`email` as `email`, `tbl_anggota`.`log` as `log`, `tbl_anggota`.`foto` as `foto`, `tbl_anggota`.`tanggal_masuk` as `tanggal_masuk`, `users`.`id` as `user_id`
FROM `users`
JOIN `tbl_anggota` ON `users`.`anggota_id` = `tbl_anggota`.`id`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Anggota.php(100): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Anggota->list_view_anggota()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Anggota))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
